billboard/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

# ckeditor urls is defined in base urls.py

urlpatterns = [
    url(r'^(?P<slug>[-\w]+)/detail/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^create/$', views.PostCreateView.as_view(), name='create'),
    url(r'^list/$', views.PostListView.as_view(), name='list'),
    url(r'^(?P<slug>[-\w]+)/update/$', views.PostUpdateView.as_view(), name='update'),
    url(r'^remove/$', views.post_remove, name='remove'),
    url(r'^detail/(?P<slug>[-\w]+)/comment/$', views.CommentCreateView.as_view(), name='comment'),
    url(r'^file_upload/$', views.BillBoardFileUploadView.as_view(), name='file_upload'),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from happypatent.users.views import GeneralSearchView

urlpatterns = [
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # My stuff
    url(r'^accounts/', include('allauth.urls')),
    url(r'^proposals/', include('proposals.urls', namespace="proposals", app_name="proposals")),
    url(r'^billboard/', include('billboard.urls', namespace="billboard", app_name="billboard")),
    url(r'^files/', include('fileattachments.urls', namespace="files", app_name="fileattachments")),
    url(r'^search/$', GeneralSearchView.as_view(), name="search-view"),
    url(r'', include('happypatent.users.urls', namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

fileattachments/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^detail/(?P<pk>[-\w]+)/$', views.FileDetailView.as_view(), name='files-detail'),
    url(r'^list/$', views.FileListView.as_view(), name='files-list'),
    url(r'^delete/$', views.FileDeleteView.as_view(), name='files-delete')
]

billboard/models.py
from __future__ import unicode_literals
from django.utils.encoding import python_2_unicode_compatible
from django.db import models
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _
from django.utils import timezone
from django.urls.base import reverse
from django.contrib.contenttypes.fields import GenericRelation
from ckeditor.fields import RichTextField
from fileattachments.models import FileAttachment
from happypatent.users.models import User


@python_2_unicode_compatible
class Post(models.Model):
    title = models.CharField(_('Title'), max_length=100)
    slug = models.SlugField(unique=True, blank=True, max_length=30)
    text = RichTextField()
    author = models.ForeignKey(verbose_name=_("Created by"),
                               to=User,
                               on_delete=models.SET_NULL,
                               null=True)
    files = GenericRelation(FileAttachment, related_query_name='post')
    created = models.DateTimeField(_('Created Time'),
                                   auto_now_add=True)

    update = models.DateTimeField(_('Latest Update'),
                                  auto_now=True,
                                  null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("billboard:detail", args=[self.slug,])

    def save(self, *args, **kwargs):
        s = "%s %d" % (self.title[:10], int(timezone.now().timestamp()))
        self.slug = slugify(s, allow_unicode=True)
        super(Post, self).save(*args, **kwargs)

    @property
    def created_by(self):
        return self.author


@python_2_unicode_compatible
class Comment(models.Model):
    text = models.TextField(max_length=150)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    created_by = models.ForeignKey(to=User,
                                   on_delete=models.SET_NULL,
                                   null=True)
    created = models.DateTimeField(_('Created Time'),
                                   auto_now_add=True)

    def __str__(self):
        return self.text[:10]

    def get_absolute_url(self):
        return reverse("billboard:detail", args=[self.post.slug,])+"#comment"

fileattachments/models.py
import os
from django.db import models
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.utils.translation import ugettext_lazy as _
from django.urls import reverse
from django.utils.encoding import python_2_unicode_compatible
from happypatent.users.models import User
from .utils import get_upload_path, file_validate


@python_2_unicode_compatible
class FileAttachment(models.Model):
    """
    - This Model can be attached to any models with any amount you like.
    - Models that would be attached to should have a GenericRelation field.
    - To get the model object attached by this FileAttachment can be done by content_object attribute.
    """
    file = models.FileField(upload_to=get_upload_path, validators=[file_validate])
    filename = models.CharField(_("File's Name"), max_length=100, blank=True)
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE)
    object_id = models.PositiveIntegerField()
    content_object = GenericForeignKey('content_type', 'object_id')
    created = models.DateTimeField(_('Created Time'), auto_now_add=True, null=True)
    created_by = models.ForeignKey(verbose_name=_("Created by"),
                                   to=User,
                                   on_delete=models.SET_NULL,
                                   null=True)

    def get_absolute_url(self):
        return reverse("files:files-detail", args=[self.pk,])

    @property
    def file_url(self):
        return self.file.url

    @property
    def file_path(self):
        return self.file.path

    def related_object_name(self):
        return str(self.content_object)

    def __str__(self):
        if self.filename:
            return self.filename
        return "Attaching %s to %s" % (self.file_path, self.related_object_name())

billboard/forms.py
from django import forms
from fileattachments.utils import file_validate
from .models import Post, Comment
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout,Fieldset,Div,ButtonHolder


class PostModelForm(forms.ModelForm):
    title = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Title"}),
                            max_length=100)

    def __init__(self, *args, **kwargs):
        super(PostModelForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.layout=Layout(
            Fieldset(
                "",
               Div(
                   "title",
                   "text",
                    css_class='box-body'
                ),
                Div(
                    Div(
                        ButtonHolder(Submit('save', 'submit',css_class='btn btn-primary pull-right')),
                        css_class='col-sm-12 '
                    ),
                    css_class='box-footer'
                )
            )
        )
    class Meta:
        model = Post
        fields = ["title", "text"]


class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]

billboard/views.py
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.views.generic.edit import CreateView, UpdateView
from django.http import HttpResponseRedirect, HttpResponseBadRequest
from django.contrib.auth.decorators import login_required
from django.db import transaction
from fileattachments.views import FileUploadView

from .models import Post, User, Comment
from .forms import PostModelForm, CommentModelForm


@transaction.non_atomic_requests
class PostDetailView(LoginRequiredMixin, DetailView):
    model = Post
    slug_field = "slug"
    slug_url_kwarg = "slug"

    def get_context_data(self, **kwargs):
        kwargs = super(PostDetailView, self).get_context_data(**kwargs)
        kwargs["comment_form"] = CommentModelForm
        kwargs["comments"] = Comment.objects.filter(post=self.object).order_by('-created')
        return kwargs


class PostCreateView(LoginRequiredMixin, CreateView):
    model = Post
    template_name = "billboard/post_create.html"
    form_class = PostModelForm
    slug_field = "slug"
    slug_url_kwarg = "slug"

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.author = User.objects.get(username=self.request.user.username)
        self.object.save()
        super(PostCreateView, self).form_valid(form)
        return HttpResponseRedirect(self.get_success_url())


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    template_name = "billboard/post_update.html"
    form_class = PostModelForm
    slug_field = "slug"
    slug_url_kwarg = "slug"


@transaction.non_atomic_requests
class PostListView(LoginRequiredMixin, ListView):
    model = Post
    paginate_by = 9
    ordering = ['-update', '-created']

    def get_context_data(self, **kwargs):
        kwargs = super(PostListView, self).get_context_data(**kwargs)
        kwargs["archive"] = self.get_archive(kwargs["object_list"])
        return kwargs

    def get_archive(self, object_list):
        arch = object_list
        archives = {}
        if arch:
            for i in range(arch[0].update.year,arch[len(arch)-1].update.year-1,-1):
                archives[i]={}
                for month in range(1,13,1):
                    archives[i][month]=[]
        for a in arch:
            archives[a.update.year][13-a.update.month].append(a)
        arch_year = list(reversed(sorted(archives.keys())))
        post_list = []
        for key in arch_year:
            adict = {key: archives[key]}
            post_list.append(adict)
        return post_list


class BillBoardFileUploadView(FileUploadView):
    model_list = [Post,]


@login_required
def post_remove(request):
    if request.method == "POST":
        post_slug = request.POST["slug"]
        try:
            obj = Post.objects.get(slug=post_slug)
        except Post.DoesNotExist:
            return HttpResponseBadRequest("Post Not Found.")
        if obj.author.username == request.user.username:
            title = obj.title
            obj.delete()
        else:
            return HttpResponseBadRequest("No privilege to do this action.")
        messages.add_message(request, messages.SUCCESS, 'You have successfully removed the post "%s".' % title)
        return HttpResponseRedirect(reverse("billboard:list"))




class CommentCreateView(LoginRequiredMixin, CreateView):
    http_method_names = [u'post']
    model = Comment
    fields = ["text"]

    def post(self, request, *args, **kwargs):
        self.post_slug = kwargs["slug"]
        return super(CommentCreateView, self).post(request, *args, **kwargs)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.post = get_object_or_404(Post, slug=self.post_slug)
        self.object.created_by = get_object_or_404(User, username=self.request.user.username)
        self.object.save()
        return HttpResponseRedirect(reverse("billboard:detail", args=(self.post_slug,))+"#comment")

billboard/templates/billboard/post_create.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Create New Post{% endblock %}
{% block content_title %}New Post{% endblock %}
{% block css %}
<style>
.blog-post-title {
  font-size: 30px;
  overflow-wrap:break-word;
  margin-top:0;
  margin-bottom:0;
  color:#2BB4B4;
}
.post-detail-box{
    padding:10px;
    float:left;
    width:75%;
    border-right:1px solid #f4f4f4;
}
.post-detail-row{
    overflow:hidden;
}
fieldset > .box-footer{
    border-top:none;
}
.box-header.with-border{
 border:none;
 padding: 15px 10px 10px 10px;
}
.box{
    border:none;
    margin: 0 auto 20px auto;
    width: 83.333333%;
     min-height:450px;
}
.form-group  input{
    border:none;
     border-bottom:1px solid #d2d6de;
}
 input#id_file{
  border-bottom:none;
 }
@media screen and (max-width: 767px){
      .box {
        width: 91.666667%;
    }
    .post-detail-box{
        width:100%;
    }
}
</style>
    {% endblock %}
{% block content %}
<script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
<div class="box ">
    <div class="post-detail-row">
        <div class="post-detail-box">
            <div class="box-header with-border">
                <h5 class="blog-post-title">Create New Post</h5>
            </div>
            <div class="box-body">
                {% crispy form %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

billboard/templates/billboard/post_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ object.title }}{% endblock %}
{% block content_title %}Billboard{% endblock %}

{% block css %}
<style>
.blog-post-title {
  font-size: 30px;
  overflow-wrap:break-word;
  margin-top:0;
  margin-bottom:0;
  color:#2BB4B4;
}
.box{
    border:none;
    margin: 0 auto 20px auto;
    width: 83.333333%;
    min-height:450px;
}
.credit-line{
  display:flex;
  justify-content: flex-start;
  align-items: baseline;
}
.credit-line > h5{
  margin-top:5px;
  margin-bottom:0;
  margin-right:5px;
}
.credit-line > a {
    padding-left: 5px;
    border-left: 1px solid #f4f4f5;
    margin-right:5px;
}
.blog-post {
  margin-bottom:10px;
  overflow-wrap:break-word;
  font-size: 16px;
  line-height: 1.4;
}
.post-detail-box,
.comment-box{
    padding:10px;
    float:left;
    width:75%;
    border-right:1px solid #f4f4f4;
}
.post-detail-box > .box-body{
    border-bottom:1px solid #f4f4f4;
}
h4{
    margin-top:0;
}
hr {
  background-color: #cbdadb;
  border: 0 none;
  color: #cbdadb;
  height: 1px;
}
.box-body,
.box-footer{
  padding: 10px 15px 10px 15px;
}
textarea{
  resize:none;
  width:100%;
  border-style:solid;
  -webkit-border-radius:4px;
  -moz-border-radius:4px;
  border-radius:4px;
  border-color:#ddd;
  border-width:1px;
  -webkit-box-shadow: 0 1px 1px rgba(0,0,0,.05);
  box-shadow: 0 1px 1px rgba(0,0,0,.05);
}
.box-header > h3,
.box-footer >h4 {
    color:#2BB4B4;
}
.box-header.with-border{
 border:none;
 padding: 15px 10px 10px 10px;
}
.post-detail-row{
    overflow:hidden;
}
.avatar a >img{
 float:left;
 width: 40px;
 height:40px;
 margin-right:10px;
 border-radius:100%;
}
.panel {
  position:relative;
}
.panel-default{
    border:none;
    border-left:2px solid #2BB4B4;
    border-radius:0;
}
.panel-default > .panel-heading{
    border:none;
    background-color:transparent;
}
@media screen and (max-width: 767px) {
    .box {
        width: 91.666667%;
    }
    .post-detail-box,
    .comment-box{
        width:100%;
    }
}
</style>
{% endblock %}

{% block content %}
 <!-- Blog Post Content column -->
<div class="box">
    <div class="post-detail-row">
        <div class="post-detail-box">
            <div class="box-header with-border">
                <h5 class="blog-post-title">{{ object.title }}</h5>
                <div class="credit-line">
                    <h5 >
                    <small>{{ object.update }} by <a href="{% url "users:detail" object.author.username %}">{{ object.author.first_name }} {{ object.author.last_name }}</a></small>
                    </h5>
                   {% if request.user == object.author %}
                    <a  href="{% url "billboard:update" object.slug %}" role="button">update </a>
                    <a id="remove-object" role="button"> remove</a>
                    <form action="{% url "billboard:remove" %}" method="post" id="remove-form">
                        {% csrf_token %}
                        <input type="hidden" name="slug" value="{{ object.slug }}">
                    </form>
                   {% endif %}
                </div>
            </div>
            <div class="box-body">
                <div class="blog-post">
                    <div>
                    {{ object.text | safe }}
                    </div>
                </div>
                <div class="panel panel-default">
                  <div class="panel-heading"><strong>Files</strong></div>
                  <div class="panel-body">
                    <ul id="files-list">
                        {% csrf_token %}
                        {% for file in object.files.all %}
                        <li>
                            <a href="{{ file.file_url }}" download > {{ file.filename }}</a>
                            {% if request.user == object.created_by  %}
                            <button class="btn btn-xs btn-danger pull-right file-remove" pk="{{ file.pk }}" delete_url="{% url "files:files-delete" %}">
                                <span class="fa fa-trash-o"></span>
                                Remove
                            </button>
                            {% endif %}
                        </li>
                        {% endfor %}
                    </ul>
                    {% if request.user == object.created_by  %}
                    <br>
                    <table class="table table-condensed">
                        <thead>
                            <tr>
                              <th>
                                  <label class="btn btn-success btn-xs" for="fileupload">
                                      <input style="display:none;" id="fileupload" type="file" name="files" upload_url="{% url "billboard:file_upload" %}" object_type="post" pk="{{ object.pk }}" multiple>
                                      <span class="fa fa-upload"></span>
                                      Upload files
                                  </label>
                              </th>
                              <th></th>
                            </tr>
                        </thead>
                        <tbody id="files-queue">
                        </tbody>
                    </table>
                    {% endif %}
                  </div>
                </div>
            </div>
        </div>
    </div>
    <!--Comment Section -->
    <div class="post-detail-row">
        <div class="comment-box">
            <div class="box-header ">
                <h3 class="box-title">Comments ({{ comments|length }})</h3>
            </div>
            <div class="box-body">
                {% for comment in comments %}
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <div class="avatar">
                            <a href="{{ comment.created_by.get_absolute_url }}"><img class="img-responsive user-photo" src="{% if comment.created_by.profile_pic %}{{ comment.created_by.profile_pic.url }}{% else %}{% static "img/blank-profile.png" %}{% endif %}"></a>
                            <a href="{{ comment.created_by.get_absolute_url }}">{{ comment.created_by.first_name }} {{ comment.created_by.last_name }}</a><br/>
                            <span class="text-muted"><small>{{ comment.created }}</small></span>
                        </div>
                    </div>
                    <div class="panel-body">
                          {{ comment.text }}
                    </div>
                </div>
                {% endfor %}
            </div>
            <div class="box-footer">
                <h4 > Leave a Comment:</h4>
                <form action="{% url "billboard:comment" object.slug %}" method="post" role="form">
                    {% csrf_token %}
                    <div class="form-group">
                        <textarea id="id_text" maxlength="150" name="text" rows="5" required=""></textarea>
                    </div>
                    <button type="submit" class="btn btn-info pull-right">Submit</button>
                </form>
            </div>
        </div>
    </div>

</div>
{% endblock %}

billboard/templates/billboard/post_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Billboard{% endblock %}
{% block content_title %}Billboard{% endblock %}

{% block css %}
<style>
.post-row {
    padding:10px;
}
.post-box{
    padding:10px;
}
.box{
   border-top:none;
   margin: 0 auto 20px auto;
   width: 83.333333%;
    min-height:450px;
}
.box-body{
  padding: 10px 15px 10px 15px;
}
.blog-post-title {
  font-size: 26px;
  overflow-wrap:break-word;
  color:#2BB4B4;
  margin-bottom: 0;
  margin-top:0;
 }
.month-bar > .row{
    padding:10px;
}
.month-bar > h3
{
   color:#ddd8d8;
   font-size:33px;
   border-bottom:1px solid #f4f4f4;
   margin-top:0;
}
.month-bar > h3 >i{
    position:relative;
    top:15px;
    left:25px;
    background:white;
}
.month-bar >h3 >i>small{
    color:#ddd8d8;
}
.post-list-content{
    color:#444;
    margin:0 auto;
    border:1px solid #ccc;
    border-radius: 5px;
    -webkit-border-radius: 5px;
    -moz-border-radius: 5px;
}
.post-list-content:hover{
   border-color:#39CCCC;
}
.post-box>a:hover{
    position:relative;
    bottom:5px;
}
.credit-line{
  display:flex;
  justify-content: flex-start;
  align-items: baseline;
  height:22.7px;
}
.credit-line > h5{
  margin-top:5px;
  margin-bottom:0;
  margin-right:5px;
}
.pager{
    margin: 0 auto 20px auto;
    width: 83.333333%;
}
.pager > span{
    position:relative;
    top:6px;
}
.pager > li.next{
    width:74px;
    height:32px;
}
@media screen and (max-width: 767px) {
    .box,
    .pager{
        width: 91.666667%;
    }
    .post-box{
    width:100%;
    }
}
</style>
{% endblock %}


{% block content %}

{% if object_list|length_is:'0' %}
<div class="box box-info">
            <div class="box-body">
                <h2>No post has been submitted yet.</h2>
                <p>Go to <a href="{% url "billboard:create" %}">Post Create</a> to create a new post.</p>
            </div>
        </div>
{% else %}
<div class="box">
<div class="post-row">
    {% for year_iterator in archive %}
            {% for month_iterator in year_iterator.values %}
                {% for month,posts in month_iterator.items %}
                    {% if posts %}
                        <div class="month-bar ">
                        {% for post in posts%}
                            {% if forloop.first %}
                                <h3><i>{{ post.update|date:"M"}} <small>{{ post.update|date:"Y"}}   </small></i></h3>
                                <div class="row">
                            {% endif %}
                            <div class="post-box col-md-4 col-sm-6">
                            <a href="{% url "billboard:detail" post.slug %}">
                                <section class="post-list-content">
                                    <div class="box-header">
                                        <h5 class="blog-post-title">{{ post.title }}</h5>
                                        <div class="credit-line">
                                        <h5>
                                        <small>{{ post.update }} by {{ post.author.first_name }} {{ post.author.last_name }}</small>
                                        </h5>
                                        </div>
                                    </div>
                                    <div class="box-body">
                                        {{ post.text|truncatewords:15|striptags }}
                                    </div>
                                </section>
                            </a>
                            </div>
                        {% endfor %}
                        </div>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endfor %}
    {% endfor %}
</div>
</div>
<!-- Pager -->
<div class="row">
    <div class="col-md-10 col-md-offset-1">
        <ul class="pager">

                {% if page_obj.has_previous %}
                <li class="previous">
                    <a href="?page={{ page_obj.previous_page_number }}">&larr; Previous</a>
                </li>
            {% endif %}

                 <span class="current">Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>

            {% if page_obj.has_next %}
                <li class="next">
                    <a href="?page={{ page_obj.next_page_number }}">Next &rarr;</a>
                </li>
            {% endif %}
        </ul>
    </div>
</div>
{% endif %}

{% endblock %}

billboard/templates/billboard/post_update.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Update Post{% endblock %}
{% block content_title %}Update Post{% endblock %}

{% block css %}
<style>
.blog-post-title {
  font-size: 30px;
  overflow-wrap:break-word;
  margin-top:0;
  margin-bottom:0;
  color:#2BB4B4;
}
.post-detail-box{
    padding:10px;
    float:left;
    width:75%;
    border-right:1px solid #f4f4f4;
}
.post-detail-row{
    overflow:hidden;
}
fieldset > .box-footer{
    border-top:none;
}
.box-header.with-border{
 border:none;
 padding: 15px 10px 10px 10px;
}
.box{
    border:none;
    margin: 0 auto 20px auto;
    width: 83.333333%;
}
.form-group  input{
    border:none;
     border-bottom:1px solid #d2d6de;
}
 input#id_file{
  border-bottom:none;
 }
@media screen and (max-width: 767px){
      .box {
        width: 91.666667%;
    }
    .post-detail-box{
        width:100%;
    }
}
</style>
{% endblock %}

{% block content %}
<script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
<div class="box ">
    <div class="post-detail-row">
        <div class="post-detail-box">
            <div class="box-header with-border">
                <h5 class="blog-post-title">Create New Post</h5>
            </div>
            <div class="box-body">
                {% crispy form %}
            </div>
        </div>
    </div>
</div>
{% endblock %}