config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from happypatent.users.views import GeneralSearchView

urlpatterns = [
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # My stuff
    url(r'^accounts/', include('allauth.urls')),
    url(r'^proposals/', include('proposals.urls', namespace="proposals", app_name="proposals")),
    url(r'^billboard/', include('billboard.urls', namespace="billboard", app_name="billboard")),
    url(r'^files/', include('fileattachments.urls', namespace="files", app_name="fileattachments")),
    url(r'^search/$', GeneralSearchView.as_view(), name="search-view"),
    url(r'', include('happypatent.users.urls', namespace='users')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

fileattachments/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^detail/(?P<pk>[-\w]+)/$', views.FileDetailView.as_view(), name='files-detail'),
    url(r'^list/$', views.FileListView.as_view(), name='files-list'),
    url(r'^delete/$', views.FileDeleteView.as_view(), name='files-delete')
]

proposals/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # Agent
    url(r'^agent/create/$', views.AgentCreateView.as_view(), name='agent-create'),
    url(r'^agent/(?P<agent_id>\d+)/detail/$', views.AgentDetailView.as_view(),
                                        name='agent-detail'),
    url(r'^agent/(?P<agent_id>\d+)/update/$', views.AgentUpdateView.as_view(),
                                        name='agent-update'),
    url(r'^agent/list/$', views.AgentListView.as_view(), name='agent-list'),
    url(r'^agent/delete/$', views.AgentDeleteView.as_view(), name='agent-delete'),
    url(r'^agent/select2/$', views.AgentSelect2View.as_view(), name='agent-select2'),

    # Patent
    url(r'^patent/create/$', views.PatentCreateView.as_view(), name='patent-create'),
    url(r'^patent/(?P<case_id>[-\w]+)/detail/$', views.PatentDetailView.as_view(),
        name='patent-detail'),
    url(r'^patent/(?P<case_id>[-\w]+)/update/$', views.PatentUpdateView.as_view(),
        name='patent-update'),
    url(r'^patent/list/$', views.PatentListView.as_view(), name='patent-list'),
    url(r'^patent/delete/$', views.PatentDeleteView.as_view(), name='patent-delete'),

    # Proposal
    url(r'^proposal/create/$', views.ProposalCreateView.as_view(), name='proposal-create'),
    url(r'^proposal/(?P<pk>\d+)/detail/$', views.ProposalDetailView.as_view(),
        name='proposal-detail'),
    url(r'^proposal/(?P<pk>\d+)/update/$', views.ProposalUpdateView.as_view(),
        name='proposal-update'),
    url(r'^proposal/list/$', views.ProposalListView.as_view(), name='proposal-list'),
    url(r'^proposal/delete/$', views.ProposalDeleteView.as_view(), name='proposal-delete'),

    # Inventor
    url(r'^inventor/create/$', views.InventorCreateView.as_view(), name='inventor-create'),
    url(r'^inventor/(?P<pk>[-\w]+)/detail/$', views.InventorDetailView.as_view(),
        name='inventor-detail'),
    url(r'^inventor/(?P<pk>[-\w]+)/update/$', views.InventorUpdateView.as_view(),
        name='inventor-update'),
    url(r'^inventor/list/$', views.InventorListView.as_view(), name='inventor-list'),
    url(r'^inventor/delete/$', views.InventorDeleteView.as_view(), name='inventor-delete'),
    url(r'^inventor/select2/$', views.InventorSelect2View.as_view(), name='inventor-select2'),

    # Control Event
    url(r'^control-event/create/$', views.ControlEventCreateView.as_view(), name='control-event-create'),
    url(r'^control-event/(?P<pk>[-\w]+)/update/$', views.ControlEventUpdateView.as_view(),
        name='control-event-update'),
    url(r'^control-event/delete/$', views.ControlEventDeleteView.as_view(), name='control-event-delete'),

    url(r'^chinese_to_english/$', views.ChineseAddressToEnglishView.as_view(), name='chinese-english-address'),

    url(r'^file_upload/$', views.ProposalFileUploadView.as_view(), name='file_upload'),

]

proposals/views.py
from django.shortcuts import redirect
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic import ListView
from django.views.generic.list import BaseListView
from django.views.generic.base import View
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseBadRequest
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import ImproperlyConfigured
from django.template.loader import render_to_string
from django.contrib import messages
from django.utils import timezone
from django.db.models import Q
from django.db import transaction
from dateutil.relativedelta import relativedelta
import geocoder
from happypatent.base.views import BaseDeleteView, BaseDataTableAjaxMixin
from fileattachments.views import FileAttachmentViewMixin, FileUploadView
from .models import Patent, Agent, User, Proposal, Inventor, ControlEvent
from .forms import PatentModelForm, AgentModelForm, InventorModelForm, ControlEventModelForm, \
    ProposalModelForm


class AjaxSelect2View(LoginRequiredMixin, BaseListView):
    """
    Base view for searching manytomany field or foreignkey field.
    Should be used with AjaxSelect2Mixin in widget.py
    """
    search_fields = []
    paginate_by = 10

    def get(self, request, *args, **kwargs):
        try:
            q = request.GET["q"]
        except KeyError:
            return HttpResponseBadRequest("No q in GET.")
        qs = [Q(**{i: q}) for i in self.search_fields]
        filter_query = qs.pop()
        for t in qs:
            filter_query |= t
        if not self.model:
            raise ImproperlyConfigured("Model parameter is missing. Please define it.")
        self.object_list = self.get_queryset(filter_query=filter_query)
        allow_empty = self.get_allow_empty()
        context = self.get_context_data(object_list=self.object_list)
        results = []
        if len(self.object_list):
            results = [
                {
                    'id': obj.pk,
                    'text': str(obj),
                }
                for obj in self.object_list
            ]
        elif "able_create_new" in request.GET and request.GET["able_create_new"] == "true":
            results.append({
                'id': -1,
                'text': "Create %s" % q
            })
        return JsonResponse({
            'items': results,
            'page': context['page_obj'].number
        }, safe=False)

    def get_queryset(self, *args, **kwargs):
        return self.model.objects.filter(kwargs["filter_query"])


class AjaxableResponseMixin(object):
    """
    Mixin to add AJAX support to a form.
    Must be used with an object-based FormView (e.g. CreateView)
    """
    def get(self, request, *args, **kwargs):
        if request.is_ajax():
            self.object = None
            context = self.get_context_data()
            s = render_to_string("proposals/ajax_modal.html",
                                 context={"form": context["form"]},
                                 request=request)
            return JsonResponse({"html": s})
        else:
            return super(AjaxableResponseMixin, self).get(request, *args, **kwargs)

    def form_invalid(self, form):
        response = super(AjaxableResponseMixin, self).form_invalid(form)
        if self.request.is_ajax():
            return JsonResponse(form.errors, status=400)
        else:
            return response

    def form_valid(self, form):
        # We make sure to call the parent's form_valid() method because
        # it might do some processing (in the case of CreateView, it will
        # call form.save() for example).
        response = super(AjaxableResponseMixin, self).form_valid(form)
        if self.request.is_ajax():
            data = {
                'id': self.object.pk,
                'text': str(self.object)
            }
            return JsonResponse(data)
        else:
            return response


class UserAppendCreateViewMixin(object):
    """ Append the user to created_by field for each model's creation inherited from _BaseModel """
    def form_valid(self, form):
        if not self.object:
            self.object = form.save(commit=False)
        self.object.created_by = User.objects.get(username=self.request.user.username)
        response = super(UserAppendCreateViewMixin, self).form_valid(form)
        return response


class CaseIDGenerator(object):
    """
    - Class that helps model 'Patent' to process latest case id.
    - Case ID Format: <year> P <case no.>.  Example: '17P010', '18P1101'
    """
    @property
    def current_year(self):
        return timezone.now().strftime("%Y")[-2:]

    def get_latest_id(self):
        return self.search_latest_id()

    @staticmethod
    def build_case_id(year, num):
        return "{0}P{1:04}".format(year, num)

    def search_latest_id(self):
        qs = Patent.objects.filter(
            Q(case_id__startswith=self.current_year) &
            Q(created__year=timezone.now().year)
        )
        max_num = 0
        for p in qs:
            s = int(p.case_id.split("P")[1].split("-")[0]) + 1
            if s > max_num:
                max_num = s
        return self.build_case_id(self.current_year, max_num)


class PatentMixin(object):
    def form_valid(self, form):
        self.object = form.save(commit=False)
        if self.object.patent_term and self.object.extended_days and self.object.country == "US":
            self.object.final_patent_term = self.object.patent_term + relativedelta(days=self.object.extended_days)
        return super(PatentMixin, self).form_valid(form)


class PatentCreateView(LoginRequiredMixin, SuccessMessageMixin, PatentMixin, UserAppendCreateViewMixin,
                       FileAttachmentViewMixin, CreateView):
    model = Patent
    template_name = 'proposals/patent_create.html'
    form_class = PatentModelForm
    success_message = "%(case_id)s was created successfully"

    def get_initial(self):
        if self.other_country:
            patent = get_object_or_404(Patent, case_id=self.case_id)
            init = {
                "case_id": self.case_id.split("-")[0],
                "chinese_title": patent.chinese_title,
                "english_title": patent.english_title,
                "inventor": patent.inventor.all()
            }
        else:
            init = {"case_id": CaseIDGenerator().get_latest_id()}
        return init

    def get(self, request, *args, **kwargs):
        if "other_country" in request.GET and request.GET["other_country"] == "true":
            self.other_country = True
            try:
                self.case_id = request.GET["case_id"]
            except KeyError:
                return HttpResponseBadRequest("Please specify case id.")
        else:
            self.other_country = False
        return super(PatentCreateView, self).get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        self.other_country = None
        post = request.POST.copy()
        if "-" not in post["case_id"]:
            post["case_id"] = post["case_id"] + "-" + post["country"]
            self.request.POST = post
        return super(PatentCreateView, self).post(request, *args, **kwargs)

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            case_id=self.object.case_id,
        )


@transaction.non_atomic_requests
class PatentDetailView(LoginRequiredMixin, DetailView):
    model = Patent
    slug_field = "case_id"
    slug_url_kwarg = "case_id"


class PatentUpdateView(LoginRequiredMixin, PatentMixin, FileAttachmentViewMixin, UpdateView):
    model = Patent
    slug_field = "case_id"
    slug_url_kwarg = "case_id"
    form_class = PatentModelForm
    template_name = "proposals/patent_update.html"


@transaction.non_atomic_requests
class PatentListView(LoginRequiredMixin, BaseDataTableAjaxMixin, ListView):
    model = Patent
    ordering = ['-update', '-created']
    paginate_by = 10
    table_fields = ["case_id", "chinese_title", "english_title", "case_status_template", "agent", "country"]


class PatentDeleteView(BaseDeleteView):
    model = Patent
    slug_field = "case_id"
    slug_url_kwarg = "case_id"
    success_url = reverse_lazy("proposals:patent-list")


class ControlEventEditMixin(object):
    def get_initial(self):
        if hasattr(self, "patent"):
            return {"case_id": self.patent.case_id}
        else:
            return {}

    def form_valid(self, form):
        if not self.object:
            self.object = form.save(commit=False)
        self.object.patent = get_object_or_404(Patent, case_id=form.cleaned_data["case_id"])
        return super(ControlEventEditMixin, self).form_valid(form)

    def get_success_url(self):
        if self.object.patent:
            return self.object.patent.get_absolute_url()
        else:
            return super(ControlEventEditMixin, self).get_success_url()


class ControlEventCreateView(LoginRequiredMixin, SuccessMessageMixin, UserAppendCreateViewMixin,
                             ControlEventEditMixin, CreateView):
    model = ControlEvent
    template_name = "proposals/control_event_create.html"
    form_class = ControlEventModelForm

    def get(self, request, *args, **kwargs):
        if "case_id" not in request.GET:
            return HttpResponseBadRequest("There's no case_id in request.")
        else:
            self.patent = get_object_or_404(Patent, case_id=request.GET["case_id"])
        if self.patent.control_event.count() >= 3:
            messages.add_message(request, messages.WARNING, 'The maximum amount of control event for each patent is 3.')
            return redirect(self.patent.get_absolute_url())
        return super(ControlEventCreateView, self).get(request, *args, **kwargs)

proposals/templates/proposals/inventor_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}Inventor{% endblock %}
{% block content_title %}Inventor{% endblock %}


{% block css %}
<style>
#inventor-title{
    color: #2BB4B4;
    margin-top:0;
    margin-bottom: 2px;
    font-size:25px;
}
#inventor-box{
    border-top-color: transparent;
    width: 83.333333%;
    margin: 0 auto;
}
#inventor-box table{
    table-layout:fixed;
}
.table.table-striped{
    border: 2px solid #f9f9f9;
}
.table-striped > tbody > tr:first-child >td{
    border-top: 2px solid #f9f9f9
}
.box-footer > h5{
     float:left;
     color: #777;
}
.box-footer > h5 >a{
     color: #2BB4B4;
}
.box-footer > h5 >a:hover{
     color: #2DA4A4;
}
.box-footer > .create-time{
    float:right;
    display:flex;
}
.box-footer > .create-time >  h5 {
    color: #777;
}
.box-footer > .create-time > h5:first-child {
    margin-right: 10px;
}
.panel-default{
     border: 2px solid #f9f9f9;
     border-radius: 0px;
     -webkit-box-shadow: none;
     box-shadow: none;
}
.panel-default .panel-body{
     border-top-color: #f9f9f9;
     border-top-width: 2px;
     padding:8px;
     min-height: 36px;
}
.panel-default .panel-body >ul{
     margin-bottom:0px;
}
.panel-default > .panel-heading {
     background-color: #f9f9f9;
     padding: 8px;
     border-bottom: 1px solid #f9f9f9;
     border-top-left-radius: 0;
     border-top-right-radius: 0;
}
.option-line{
   float:right;
   padding-left:5px;
   position:relative;
   top:5px;
}
.option-line > a {
   border-right: 1px solid #f4f4f5;
   margin-right:5px;
   padding-right:5px;
}
.option-line > a:first-child{
    padding-left:10px;
    border-left:1px solid #f4f4f5;
}
@media screen and (max-width: 767px){
    #inventor-box{
        width: 91.666667%;
   }
}
@media screen and (max-width: 490px){
    .option-line{
        float:none;
        text-align:center;
    }
    #inventor-title{
        display:block;
        text-align: center;
    }
    .box-footer > h5,
    .box-footer > .create-time{
        float: none;
        position: relative;
    }
    .box-footer > h5{
        margin-top:0;
        top: -10px;
        margin-bottom:0;
        text-align: center;
    }
    .box-footer > .create-time{
        top:-5px;
        justify-content:center;
        text-align:center
    }
}
</style>
{% endblock css %}

{% block content %}
<div id="inventor-box" class="box box-info">
    <div class="box-header with-border">
      <h3 id="inventor-title" class="box-title ">{{ object.chinese_name }}</h3>
      <div class="option-line">
          {% if request.user == object.created_by  %}
          <a href="{% url "proposals:inventor-update" object.pk %}" role="button">Update</a>
          <a id="remove-object">Remove</a>
          <form action="{% url "proposals:inventor-delete" %}" id="remove-form" method="post">
              {% csrf_token %}
              <input type="hidden" name="slug_field" value="{{ object.pk }}">
          </form>
          {% endif %}
      </div>
    </div>
    <div class="box-body">
        <div class="row">
            <div class="col-md-6">
                <table class="table table-striped">
                <tbody>
                    <tr>
                        <td><strong>Chinese name</strong></td>
                        <td>{{ object.chinese_name }}</td>
                    </tr>
                    <tr>
                        <td><strong>English name</strong></td>
                        <td>{{ object.english_name }}</td>
                    </tr>
                    <tr>
                        <td><strong>ID Number</strong></td>
                        <td>{% if object.id_number %}{{ object.id_number }}{% else %}None{% endif %}</td>
                    </tr>
                    <tr>
                        <td><strong>Department</strong></td>
                        <td>{{ object.department }}</td>
                    </tr>
                    <tr>
                        <td><strong>Email</strong></td>
                        <td>{% if object.email %}{{ object.email }}{% else %}None{% endif %}</td>
                    </tr>
                </tbody>
                </table>
            </div>
            <div class="col-md-6">
                <table class="table table-striped">
                <tbody>
                    <tr>
                        <td><strong>Country</strong></td>
                        <td>{{ object.country }}</td>
                    </tr>
                    <tr>
                        <td><strong>Post Office Address</strong></td>
                        <td>{{ object.post_address }}</td>
                    </tr>
                    <tr>
                        <td><strong>English Address</strong></td>
                        <td>{{ object.english_address }}</td>
                    </tr>
                    <tr>
                        <td><strong>Phone Number</strong></td>
                        <td>{{ object.phone_number }}</td>
                    </tr>
                </tbody>
                </table>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-default">
                  <div class="panel-heading"><strong>Remarks</strong></div>
                  <div class="panel-body">
                    {{ object.remarks }}
                  </div>
                </div>
            </div>
        </div>
    </div>
    <div class="box-footer">
        <h5><br/>Created by <a href="{{ object.created_by.get_absolute_url }}">{{ object.created_by.username }}</a></h5>
        <div class="create-time">
            <h5>Created:<br/>{{ object.created }}</h5>
            <h5>Last updated:<br/>{{ object.update }}</h5>
        </div>
    </div>
</div>


{% endblock content %}

proposals/templates/proposals/proposal_detail.html
{% extends "base.html" %}
{% block title %}Proposal{% endblock %}
{% block content_title %}Proposal{% endblock %}

{% block css %}
<style>
#agent-title{
    color: #2BB4B4;
    margin-top:0;
    margin-bottom: 2px;
    font-size:25px;
}
#agent-box{
    border-top-color: transparent;
    width:  83.33333%;
    margin: 0 auto;
     min-height:450px;
}
#agent-box > .box-header.with-border {
    border-bottom: 1px solid #f4f4f4;
}
.table.table-striped{
    border: 2px solid #f9f9f9;
}
.table-striped > tbody > tr:first-child >td{
    border-top: 2px solid #f9f9f9
}
.box-footer > h5{
    float:left;
    color: #777;
}
.box-footer > h5 >a,
#files-list> li >a{
    color: #2DA4A4;
}
.box-footer > h5 >a:hover,
#files-list> li >a:hover{
    color: #39CCCC;
}
#file-table label.btn-success{
    background-color:#2BB4B4;
    border-color:transparent;
}
#file-table label.btn-success:hover{
    background-color:#39CCCC;
}
#files-list{
    padding-left:0;
}
#files-list>li{
    margin-bottom:5px;
    border-bottom:1px solid #f4f4f4;
    list-style: none;
    padding: 3px;
}
#files-list .btn-danger{
    background-color:transparent;
    color:#d43f3a;
    border-color:transparent;
}
#files-list .btn-danger:hover{
    background-color:transparent;
    color:#761c19;;
    border-color:transparent;
}
#files-list >li >div:first-child{
    display:inline;
    word-wrap:break-word;
    width:70%;

}
#files-list >li >div:nth-child(2){
    text-align:right;
}
#files-queue{
    padding:3px;
}
#files-queue >li >div:first-child{
    display:inline;
    word-wrap:break-word;
    width:70%;

}
#files-queue >li  >div:nth-child(2){
    text-align:right;
}
#files-queue  button:nth-child(2){
    border-right:1px solid #f4f4f4;
}
#files-queue > li{
    margin-bottom:5px;
    border-bottom:1px solid #f4f4f4;
    list-style: none;
    padding: 3px;
}
#files-queue  button{
    background-color:transparent;
    border-color:transparent;
    color:#3c8dbc
}
#files-queue  button:hover {
    background-color: transparent;
    border-color: transparent;
    color: #72afd2;
}
.box-footer > .create-time{
    float:right;
    display:flex;
}
.box-footer > .create-time >  h5 {
    color: #777;
}
.box-footer > .create-time > h5:first-child {
    margin-right: 10px;
}
.panel-default{
    border: 2px solid #f9f9f9;
    border-radius: 0;
    -webkit-box-shadow: none;
    box-shadow: none;
}
.panel-default .panel-body{
    border-top-color: #f9f9f9;
    border-top-width: 2px;
    padding:8px;
    min-height: 36px;
}
.panel-default .panel-body >ul{
    margin-bottom:0;
}
.panel-default > .panel-heading {
    background-color: #f9f9f9;
    padding: 8px;
    border-bottom: 1px solid #f9f9f9;
    border-top-left-radius: 0;
    border-top-right-radius: 0;
}
.option-line{
    float:right;
    padding-left:5px;
    position:relative;
    top:5px;
}
.option-line > a {
    border-right: 1px solid #f4f4f5;
    margin-right:5px;
    padding-right:5px;
}
.option-line > a:first-child{
    padding-left:10px;
    border-left:1px solid #f4f4f5;
}
@media screen and (max-width: 767px){
    #agent-box{
        width: 91.666667%;
   }
}
@media screen and (max-width: 490px){
   .option-line{
       float:none;
       padding-left:5px;
       position:relative;
       top:5px;
       text-align:center;
   }
   #agent-title{
       display:block;
       text-align: center;
     }
    .box-footer > h5,
    .box-footer > .create-time{
        float: none;
        position: relative;
    }
    .box-footer > h5{
        margin-top:0;
        top: -10px;
        margin-bottom:0;
        text-align: center;
    }
    .box-footer > .create-time{
        top:-5px;
        justify-content:center;
        text-align:center
    }
}
</style>
{% endblock css %}


{% block content %}
<div id="agent-box" class="box box-info ">
    <div class="box-header with-border">
      <h3 id="agent-title" class="box-title ">{{ object.chinese_title }}</h3>
      <div class="option-line">
          {% if request.user == object.created_by  %}
          <a href="{% url "proposals:proposal-update" object.pk %}" role="button">Update</a>
          <a id="remove-object">Remove</a>
          <form action="{% url "proposals:proposal-delete" %}" id="remove-form" method="post">
              {% csrf_token %}
              <input type="hidden" name="slug_field" value="{{ object.pk }}">
          </form>
          {% endif %}
      </div>
    </div>
    <div class="box-body">
        <div class="row">
            <div class="col-md-6">
                <table class="table table-striped">
                <tbody>
                    <tr>
                        <td><strong>Proposal ID</strong></td>
                        <td>{{ object.proposal_id }}</td>
                    </tr>
                    <tr>
                        <td><strong>Chinese Title</strong></td>
                        <td>{{ object.chinese_title }}</td>
                    </tr>
                    <tr>
                        <td><strong>English Title</strong></td>
                        <td>{{ object.english_title }}</td>
                    </tr>
                </tbody>
                </table>
            </div>
            <div class="col-md-6">
                <table class="table table-striped">
                <tbody>
                    {% for person in object.inventors.all %}
                        <tr>
                            <td><strong>Inventor({{ forloop.counter }})</strong></td>
                            <td><a href="{{ person.get_absolute_url }}">{{ person.chinese_name }}</a></td>
                        </tr>
                        {% empty %}
                        <tr>
                            <td><strong>No inventor in this list.</strong></td>
                        </tr>
                    {% endfor %}
                    <tr>
                        <td><strong>Department</strong></td>
                        <td>{% if object.department %}{{ object.department }}{% else %}None{% endif %}</td>
                    </tr>
                    <tr>
                        <td><strong>Technique category</strong></td>
                        <td>{% if object.category %}{{ object.category }}{% else %}None{% endif %}</td>
                    </tr>
                </tbody>
                </table>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-md-6">
                <table class="table table-striped">
                <tbody>
                    <tr>
                        <td><strong>Proposal Date</strong></td>
                        <td>{% if object.proposal_date %}{{ object.proposal_date|date:"SHORT_DATE_FORMAT" }}{% else %}None{% endif %}</td>
                    </tr>
                    <tr>
                        <td><strong>Default Filing Countries</strong></td>
                        <td>{% if object.country %}{{ object.country }}{% else %}None{% endif %}</td>
                    </tr>
                    <tr>
                        <td><strong>Applied field and performance</strong></td>
                        <td>{% if object.performance %}{{ object.performance }}{% else %}None{% endif %}</td>
                    </tr>
                </tbody>
                </table>
            </div>
            <div class="col-md-6">
                <table class="table table-striped">
                <tbody>
                    <tr>
                        <td><strong>Appraisal date</strong></td>
                        <td>{% if object.appraisal_date %}{{ object.appraisal_date|date:"SHORT_DATE_FORMAT" }}{% else %}None{% endif %}</td>
                    </tr>
                    <tr>
                        <td><strong>Appraisal Results</strong></td>
                        <td>{% if object.appraisal_result %}{{ object.appraisal_result_template }}{% else %}None{% endif %}</td>
                    </tr>
                    <tr>
                        <td><strong>Abstract</strong></td>
                        <td>{% if object.abstract %}{{ object.abstract }}{% else %}None{% endif %}</td>
                    </tr>
                </tbody>
                </table>
            </div>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="panel panel-default">
                  <div class="panel-heading"><strong>Remarks</strong></div>
                  <div class="panel-body">
                    {{ object.remarks }}
                  </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="panel panel-default">
                  <div class="panel-heading"><strong>Files</strong></div>
                  <div class="panel-body">
                    <ul id="files-list">
                        {% csrf_token %}
                        {% for file in object.files.all %}
                        <li>
                            <div >
                                <a href="{{ file.file_url }}" download > {{ file.filename }}</a>
                            </div>
                            {% if request.user == object.created_by  %}
                            <div >
                                <button class="btn btn-xs btn-danger  file-remove" pk="{{ file.pk }}" delete_url="{% url "files:files-delete" %}">
                                <span class="fa fa-trash-o"></span>
                                Remove
                                </button>
                            </div>
                            {% endif %}
                        </li>
                        {% endfor %}
                    </ul>
                    {% if request.user == object.created_by  %}

                    <div id="file-table">
                            <label class="btn btn-success btn-xs" for="fileupload">
                                      <input style="display:none;" id="fileupload" type="file" name="files" upload_url="{% url "proposals:file_upload" %}" object_type="proposal" pk="{{ object.pk }}" multiple>
                                      <span class="fa fa-upload"></span>
                                      Upload files
                                  </label>
                    </div>
                        <ul id="files-queue">
                        </ul>
                    {% endif %}
                  </div>
                </div>
            </div>
        </div>
    </div>
    <div class="box-footer">
         <h5 ><br/>Created by <a href="{{ object.created_by.get_absolute_url }}">{{ object.created_by.username }}</a></h5>
         <div class="create-time">
             <h5 >Created:<br>{{ object.created }}</h5>
             <h5 >Last updated:<br>{{ object.update }}</h5>
         </div>
    </div>
</div>
{% endblock content %}